set -x

qsub run_nam_catchup_prdgen_alaska_tm03_f00.sh
qsub run_nam_catchup_prdgen_alaska_tm03_f01.sh
qsub run_nam_catchup_prdgen_conus_tm03_f00.sh
qsub run_nam_catchup_prdgen_conus_tm03_f01.sh
qsub run_nam_catchup_prdgen_tm03_f00.sh
qsub run_nam_catchup_prdgen_tm03_f01.sh
