set -x

qsub run_nam_catchup_post_alaska_tm03_f00.sh
qsub run_nam_catchup_post_alaska_tm03_f01.sh
qsub run_nam_catchup_post_conus_tm03_f00.sh
qsub run_nam_catchup_post_conus_tm03_f01.sh
qsub run_nam_catchup_post_tm03_f00.sh
qsub run_nam_catchup_post_tm03_f01.sh
