set -x

qsub run_nam_catchup_prdgen_alaska_tm06_f00.sh
qsub run_nam_catchup_prdgen_alaska_tm06_f01.sh
qsub run_nam_catchup_prdgen_conus_tm06_f00.sh
qsub run_nam_catchup_prdgen_conus_tm06_f01.sh
qsub run_nam_catchup_prdgen_tm06_f00.sh
qsub run_nam_catchup_prdgen_tm06_f01.sh
