#!/bin/bash
set -xa

export HOMEnam=$PACKAGEROOT/nam.${nam_ver}_rocoto
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=${jobid:?}

# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS

export procs=28
export procspernode=28
export threads=1
export OMP_NUM_THREADS=1
export OMP_PLACES=cores

  # Got these from the FV3GFS env.
  export MPI_LABELIO=YES
  export MP_STDOUTMODE="ORDERED"

########################################################
# Execute the script.
${HOMEnam}/scripts/exnam_post.sh
jerr=$?
########################################################

cat $pgmout
date
msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-YES} = NO ] ; then rm -rf $DATA ; fi

exit $jerr
