#!/bin/bash
set -xa

export HOMEnam=$PACKAGEROOT/nam.${nam_ver}_rocoto
export JJOBSnam=$HOMEnam/jobs
export WKDIRNAME=nam_${cyc}_${tmmark}_${envir}

# Setup directories and common environment variables

. ${JJOBSnam}/JNAM_ENVARS

if [ $tmmark = tm00 ] ; then
# no hyperthreading (41 nodes)
  export ntasks=2583
  export ppn=63
  export threads=2
# w/hyperthreading (38 nodes)
# export ntasks=2496
# export ppn=64
# export threads=2
else
  export ntasks=1024
  export ppn=64
  export threads=2
fi

# Got these from the FV3GFS env.
export MPI_LABELIO=YES
export MP_STDOUTMODE="ORDERED"

#Forecast job settings
# OMP settings
ulimit -s unlimited
ulimit -a
export OMP_PROC_BIND=true
export OMP_NUM_THREADS=$threads
export OMP_STACKSIZE=1G

export MPICH_ABORT_ON_ERROR=1
export MALLOC_MMAP_MAX_=0
export MALLOC_TRIM_THRESHOLD_=134217728
export FORT_FMT_NO_WRAP_MARGIN=true
export MPICH_REDUCE_NO_SMP=1
export FOR_DISABLE_KMP_MALLOC=TRUE
export FI_OFI_RXM_RX_SIZE=40000
export FI_OFI_RXM_TX_SIZE=40000
export MPICH_OFI_STARTUP_CONNECT=1
export MPICH_OFI_VERBOSE=1
export MPICH_OFI_NIC_VERBOSE=1

########################################################
# Execute the script.
${HOMEnam}/scripts/exnam_fcst.sh
jerr=$?
########################################################

cat $pgmout errfile
date
msg="JOB $job HAS COMPLETED NORMALLY"
postmsg "$msg"

cd $DATA
exit $jerr
