set -x

qsub run_nam_catchup_post_alaska_tm04_f00.sh
qsub run_nam_catchup_post_alaska_tm04_f01.sh
qsub run_nam_catchup_post_conus_tm04_f00.sh
qsub run_nam_catchup_post_conus_tm04_f01.sh
qsub run_nam_catchup_post_tm04_f00.sh
qsub run_nam_catchup_post_tm04_f01.sh
