set -x

qsub run_nam_catchup_post_alaska_tm05_f00.sh
qsub run_nam_catchup_post_alaska_tm05_f01.sh
qsub run_nam_catchup_post_conus_tm05_f00.sh
qsub run_nam_catchup_post_conus_tm05_f01.sh
qsub run_nam_catchup_post_tm05_f00.sh
qsub run_nam_catchup_post_tm05_f01.sh
